

CREATE SEQUENCE  "TRAINING"."TEAM_SEQUENCE"  MINVALUE 100 MAXVALUE 999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;




 CREATE TABLE "TRAINING"."TEAM" 
   (	"TEAM_NAME" VARCHAR2(20 BYTE), 
	"TEAM_SEQUENCE" NUMBER NOT NULL ENABLE, 
	"CLIENT_NAME" VARCHAR2(20 BYTE), 
	"CLIENT_LOCATION" VARCHAR2(20 BYTE), 
	 CONSTRAINT "TEAM_PK" PRIMARY KEY ("TEAM_SEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;





 CREATE TABLE "TRAINING"."USERS_TEAM" 
   (	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"DESIGNATION" VARCHAR2(20 BYTE), 
	"TEAM_SEQUENCE" NUMBER, 
	"PASSWORD" VARCHAR2(20 BYTE), 
	 CONSTRAINT "USERS_TEAM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING"  ENABLE, 
	 CONSTRAINT "USERS_TEAM_FK1" FOREIGN KEY ("TEAM_SEQUENCE")
	  REFERENCES "TRAINING"."TEAM" ("TEAM_SEQUENCE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;






  CREATE TABLE "TRAINING"."EVENTS" 
   (	"EVENT_TITLE" VARCHAR2(20 BYTE), 
	"EVENT_DATE" DATE, 
	"EVENT_PLACE" VARCHAR2(20 BYTE), 
	"TEAM_SEQUENCE" NUMBER, 
	 CONSTRAINT "EVENTS_TEAM_FK1" FOREIGN KEY ("TEAM_SEQUENCE")
	  REFERENCES "TRAINING"."TEAM" ("TEAM_SEQUENCE") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;




  CREATE TABLE "TRAINING"."USER_LOGIN" 
   (	"EMAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	 CONSTRAINT "USER_LOGIN_USERS_TEAM_FK1" FOREIGN KEY ("EMAIL")
	  REFERENCES "TRAINING"."USERS_TEAM" ("ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TRAINING" ;
 
 
 
